//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAndVendor
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public bool IsCustomer { get; set; }
        public string Name { get; set; }
        public string VAT_NIP { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Country { get; set; }
        public string Branch { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public double MaxCredit { get; set; }
        public string Notes { get; set; }
    }
}
