//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispatchForm()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string TransportOrderNumber { get; set; }
        public string ExternalReference { get; set; }
        public Nullable<int> TruckID { get; set; }
        public string TruckName { get; set; }
        public Nullable<int> TrailerID { get; set; }
        public string TrailerName { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public string LoadingAddress { get; set; }
        public Nullable<System.DateTime> LoadingDateTimeFrom { get; set; }
        public Nullable<System.DateTime> LoadingDateTimeTo { get; set; }
        public string LoadingReferenceNumber { get; set; }
        public string UnloadingAddress { get; set; }
        public Nullable<System.DateTime> UnloadingDateTimeFrom { get; set; }
        public Nullable<System.DateTime> UnloadingDateTimeTo { get; set; }
        public string UnloadingReferenceNumber { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<int> NumberOfLoads { get; set; }
        public string LoadDetails { get; set; }
        public string RouteInformation { get; set; }
        public string CustomsClearance { get; set; }
        public Nullable<bool> TollRoads { get; set; }
        public Nullable<bool> VignettesNeeded { get; set; }
        public string FerryInformation { get; set; }
        public string ContactInformation { get; set; }
        public string MultiStopPlanReference { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LoadedDateTime { get; set; }
        public Nullable<System.DateTime> UnloadedDateTime { get; set; }
        public Nullable<System.DateTime> DriverLastReadDateTime { get; set; }
        public Nullable<bool> ADRCategory21 { get; set; }
        public Nullable<bool> ADRCategory22 { get; set; }
        public Nullable<bool> ADRCategory23 { get; set; }
        public Nullable<bool> ADRCategory3 { get; set; }
        public Nullable<bool> ADRCategory41 { get; set; }
        public Nullable<bool> ADRCategory42 { get; set; }
        public Nullable<bool> ADRCategory43 { get; set; }
        public Nullable<bool> ADRCategory51 { get; set; }
        public Nullable<bool> ADRCategory52 { get; set; }
        public Nullable<bool> ADRCategory61 { get; set; }
        public Nullable<bool> ADRCategory62 { get; set; }
        public Nullable<bool> ADRCategory8 { get; set; }
        public Nullable<bool> ADRCategory9 { get; set; }
        public Nullable<bool> NotifyDriver { get; set; }
        public Nullable<bool> Loaded { get; set; }
        public Nullable<bool> Unloaded { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string FirebaseDocumentId { get; set; }
        public string FirebaseDocumentRef { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
