//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> DispatchFormId { get; set; }
        public string TransportOrderNumber { get; set; }
        public string OtherReference { get; set; }
        public string FileCloudURL { get; set; }
        public string FileCloudName { get; set; }
        public string FileLocalPath { get; set; }
        public string FileLocalName { get; set; }
        public string Type { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FirebaseDocumentId { get; set; }
        public string FirebaseDocumentRef { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual DispatchForm DispatchForm { get; set; }
    }
}
