//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiltonDBEntities : DbContext
    {
        public MiltonDBEntities()
            : base("name=MiltonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<CashNote> CashNotes { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomerAndVendor> CustomerAndVendors { get; set; }
        public virtual DbSet<DispatchForm> DispatchForms { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Drawer> Drawers { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual DbSet<InvoicingSheet> InvoicingSheets { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MultiStopDetail> MultiStopDetails { get; set; }
        public virtual DbSet<MultiStopHeader> MultiStopHeaders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductUnit> ProductUnits { get; set; }
        public virtual DbSet<StoreLog> StoreLogs { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trailer> Trailers { get; set; }
        public virtual DbSet<TruckExpens> TruckExpenses { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<UnitName> UnitNames { get; set; }
        public virtual DbSet<UserAccessProfile> UserAccessProfiles { get; set; }
        public virtual DbSet<UserAccessProfileDetail> UserAccessProfileDetails { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSettingsProfile> UserSettingsProfiles { get; set; }
        public virtual DbSet<UserSetttingsProfileProperty> UserSetttingsProfileProperties { get; set; }
        public virtual DbSet<CashNoteLink> CashNoteLinks { get; set; }
    }
}
