//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicingSheet
    {
        public int Id { get; set; }
        public string TransportOrderNumber { get; set; }
        public string TruckFireStoreRef { get; set; }
        public string TruckName { get; set; }
        public Nullable<int> TruckId { get; set; }
        public string ExternalReference { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string CurrencyDocumentId { get; set; }
        public Nullable<double> VATPercentage { get; set; }
        public string NIPEUVATNumber { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public string BuyerName { get; set; }
        public string BuyerAddress { get; set; }
        public string BuyerEmail { get; set; }
        public Nullable<int> DeadLine { get; set; }
        public string DepartureLocation { get; set; }
        public string ArrivalLocation { get; set; }
        public Nullable<double> DistanceKM { get; set; }
        public Nullable<double> TotalOrderWorthNET { get; set; }
        public Nullable<double> TotalOrderWorthGROSS { get; set; }
        public Nullable<double> RatePerKM { get; set; }
        public Nullable<System.DateTime> DateTimeCompleted { get; set; }
        public Nullable<System.DateTime> DateTimeCMRSent { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceIssuedDate { get; set; }
        public string InvoiceLink { get; set; }
        public string PaymentDeadline { get; set; }
        public Nullable<System.DateTime> PaymentDeadlineDate { get; set; }
        public Nullable<System.DateTime> DatePaymentReceived { get; set; }
        public string FreightExchange { get; set; }
        public string Notes { get; set; }
        public string FactoringAgent { get; set; }
        public string ParentInvoice { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> DispatchFormId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public byte[] ChildInvoices { get; set; }
        public string FirebaseDocumentId { get; set; }
        public string FirebaseDocumentRef { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
