//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int ItemId { get; set; }
        public int ItemUnitId { get; set; }
        public double ItemQty { get; set; }
        public double Price { get; set; }
        public double TotalPrice { get; set; }
        public bool Nontaxable { get; set; }
        public double CostValue { get; set; }
        public double TotalCostValue { get; set; }
        public double DiscountRatio { get; set; }
        public double DiscountValue { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> SourceRowId { get; set; }
    }
}
