//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiStopHeader
    {
        public int Id { get; set; }
        public string MultiStopRef { get; set; }
        public string TransportOrderNumber { get; set; }
        public Nullable<int> DispatchFormId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string FirebaseDocumentId { get; set; }
        public string FirebaseDocumentRef { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
