//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SalesAccountId { get; set; }
        public int SalesReturnAccountId { get; set; }
        public int InventoryAccountId { get; set; }
        public int CostOfSoldGoodsAccountId { get; set; }
        public int DiscountReceivedAccountId { get; set; }
        public int DiscountAllowedAccountId { get; set; }
    }
}
