//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        public int Id { get; set; }
        public string TrailerName { get; set; }
        public string TrailerRegistrationNumber { get; set; }
        public string TrailerFullName { get; set; }
        public Nullable<double> CargoHeight { get; set; }
        public Nullable<double> CargoWidth { get; set; }
        public Nullable<double> CargoLength { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> LoadingWeight { get; set; }
        public Nullable<System.DateTime> TrailerTechnicalInspectionExpiryDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string FirebaseDocumentId { get; set; }
        public string FirebaseDocumentRef { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
