//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckExpens
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> UserInputDate { get; set; }
        public string Location { get; set; }
        public Nullable<double> AmountOfLiters { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public string Currency { get; set; }
        public string ReceiptNumber { get; set; }
        public string PaymentMethod { get; set; }
        public string Description { get; set; }
        public string CountryOfToll { get; set; }
        public string TruckName { get; set; }
        public Nullable<int> TruckId { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Odometer { get; set; }
        public Nullable<double> DistanceTravelled { get; set; }
        public Nullable<double> Consumption { get; set; }
        public string GUID { get; set; }
        public System.Data.Entity.Spatial.DbGeography LocationGeo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string FirebaseDocumentId { get; set; }
        public string FirebaseDocumentRef { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
